# docker run --rm -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:14-alpine

version: '2'
services:
  db:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - './initdb.d:/docker-entrypoint-initdb.d'
